name: Code formatting
on:
  pull_request:
    branches:
      - main
      - master
      - pilot
      - develop
      - RC
      - RC-[0-9]+
      - rc-[0-9]+

    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # - name: Get changes
      #   run: |
      #       CHANGED_FILES=$(git diff --name-only -r HEAD^1 HEAD)
      #       echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # - name: Get list of changed files
      #   id: changed-files
      #   run: |
      #     CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
      #     echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
      - name: Run prettier check
        run: |
          CHANGED_FILES=$(git diff --name-only -r HEAD^1 HEAD)
          npm run format:check-files $CHANGED_FILES
        # if: ${{ env.CHANGED_FILES != '' }}
        # run: npm run format:check-files $CHANGED_FILES
