name: Code formatting
on:
  pull_request:
    branches:
      - main
      - master
      - pilot
      - develop
      - RC
      - RC-[0-9]+
      - rc-[0-9]+

    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # For PRs the action/checkout step creates a detached head which is simulating a merge of the PR into the target branch.
          # Using "fetch-depth: 2" here allows us to do a git diff between the last two commits,
          # and only run formatting cheks on the files that changed (see the "Run prettier check" step)
          # https://stackoverflow.com/a/74268200
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run prettier check
        run: |
          CHANGED_FILES=$(git diff --name-only -r HEAD^1 HEAD)
          npm run format:check-files $CHANGED_FILES
